[package]
name = "gst-plugin-openai"
version.workspace =true
edition.workspace = true
rust-version.workspace = true
description = "A GStreamer filter implementing conversation with the OpenAI API"
repository = "https://github.com/tiwater/ticos-agent"

[dependencies]
gst.workspace = true
gst-base.workspace = true
gst-audio.workspace = true
futures = "0.3"
futures-util = "0.3"
tokio = { version = "1", features = [ "full" ] }
async-tungstenite = { version = "0.28", features = ["tokio", "tokio-runtime", "tokio-native-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
atomic_refcell = "0.1"
http = { version = "1.0" }
url = "2"
base64 = "0.22"
lazy_static = "1.4"

[dev-dependencies]
gst-check.workspace = true

[build-dependencies]
gst-plugin-version-helper.workspace = true

[lib]
name = "gstopenai"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[features]
static = []
capi = []

[package.metadata.capi]
min_version = "0.8.0"

[package.metadata.capi.header]
enabled = false

[package.metadata.capi.library]
install_subdir = "gstreamer-1.0"
versioning = false

[package.metadata.capi.pkg_config]
requires_private = "gstreamer-1.0, gstreamer-base-1.0, gobject-2.0, glib-2.0, gmodule-2.0"
